<?php

use Win\Alert\Session;
use Win\Mvc\View;
use Win\Widget\ReCaptcha;

/* @var $this View */
?>
<main>
	<h1>Recuperar Senha</h1>

	<form method="post" action="login/recuperar-senha/">
		<?php Session::showAlerts(); ?>

		<fieldset>
			<input type="text" name="email" value="<?= $this->app->getUser()->getEmail(); ?>" required placeholder="Seu E-mail" />
		</fieldset>

		<fieldset>
			<div class="g-recaptcha" data-sitekey="<?= ReCaptcha::$siteKey; ?>"></div>
		</fieldset>

		<div class="form-buttons">
			<button type="submit" name="submit" class="btn" value="1">Enviar</button>
		</div>

		<div class="text-center">
			<a href="login/">Voltar ao Login</a>
		</div>
	</form>

</main>
<script src='https://www.google.com/recaptcha/api.js'></script>